### ISSUE TITLE
Tweaker: TODO LIST

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/Fake.Net#2]
- [ ] Hide most of toolbar in user route (these won't be created for a long time, if ever), just keep Home and make it link to index route
- [ ] Make logged in page fetch and display tweaks (posts)
- [ ] Make logged in page have a "tweak this!" form at the top for adding new tweaks
- [ ] Make logging out possible
- [ ] Design tweak effects and implement them
- [ ] Add "about" link to some sort of footer to link back to Fake.Net / the GitHub ?
- [ ] Make adding/changing name possible
- [ ] MIGRATION: Rename `icon` to `avatar`
- [ ] Make changing/uploading avatar possible
- [ ] MIGRATION: Add boolean `is_dummy` to say whether or not is dummy user (default false)
- [ ] Make going to non-existent users create a dummy user and populate it
- [ ] Make mentions possible with @'s
- [ ] Add notifications (and unhide toolbar bit about this!)
- [ ] Make following possible and show other users' tweaks in your feed
