### ISSUE TITLE
ToDo: Rewrite README instructions

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/Fake.Net#3]
Maybe not these things exactly, but possibly
- [ ] section for general guide to setting up a Lapis environment
- [ ] section that is specific to running the server
- [ ] section that is specific to setting up a dev environment

**Comment by TangentFoxy** [comment]
Don't forget migrations need a specified environment! This is why my migrations were failing on Debian (I think, untested)!
